{% set name = "tf-keras" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tf_keras-{{ version }}.tar.gz
    sha256: ebf744519b322afead33086a2aba872245473294affd40973694f3eb7c7ad77d
  - fn: LICENSE
    url: https://raw.githubusercontent.com/keras-team/tf-keras/v{{ version }}/LICENSE
    sha256: 58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd

build:
  # skip osx-64 because of failed import of tf-keras:
  # ImportError: cannot import name 'training_distributed_v1' from 'tensorflow.python.keras.engine'
  # tensorflow unavailable for python 3.13
  skip: True  # [py>=313 or (osx and x86_64)]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    # added scipy from requirements.txt because it seems to be used in production code in tf_keras/preprocessing/image.py
    # and is not explicitly listed as an optional dependency
    - scipy
    - tensorflow >=2.18,<2.19

test:
  imports:
    - tf_keras
  commands:
    - pip check
  requires:
    - pip
    - python
    # added pandas from requirements.txt because it is used in unit tests
    - pandas

about:
  home: https://keras.io/
  summary: Deep learning for humans.
  description: |
    Keras is an API designed for human beings, not machines. Keras follows best practices for reducing cognitive load:
    it offers consistent & simple APIs, it minimizes the number of user actions required for common use cases, and it
    provides clear & actionable error messages. Keras also gives the highest priority to crafting great documentation
    and developer guides.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://www.tensorflow.org/api_docs/python/tf/keras
  dev_url: https://github.com/keras-team/tf-keras

extra:
  recipe-maintainers:
    - conda-forge/keras
