{% set name = "tf-keras" %}
{% set version = "2.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tf_keras-{{ version }}.tar.gz
    sha256: fda97c18da30da0f72a5a7e80f3eee343b09f4c206dad6c57c944fb2cd18560e
  - fn: LICENSE
    url: https://raw.githubusercontent.com/keras-team/tf-keras/v{{ version }}/LICENSE
    sha256: 58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    # added scipy from requirements.txt becaus it seems to be used in production code in tf_keras/preprocessing/image.py
    # and is not explicitly listed as an optional dependency
    - scipy
    - numpy >=1.26.0,<2.1.0
    - tensorflow >=2.17,<2.18

test:
  imports:
    - tf_keras
  commands:
    - pip check
  requires:
    - pip
    - python
    # added pandas from requirements.txt because it is used in unit tests
    - pandas

about:
  home: https://keras.io/
  dev_url: https://github.com/keras-team/tf-keras
  summary: Deep learning for humans.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/keras
